# Generated by Django 6.0.4 on 2026-05-24 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locais', '0001_initial'),
        ('users', '0001_initial'),
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('data_inicio_desejada', models.DateField()),
                ('data_fim_desejada', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendente', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='users.cliente')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_analisadas', to='users.funcionario')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='locais.local')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='veiculo.veiculo')),
            ],
        ),
    ]
