# Generated by Django 6.0.4 on 2026-05-24 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupo_veiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('renavam', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano_fabricacao', models.IntegerField()),
                ('ano_modelo', models.IntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('quilometragem', models.FloatField()),
                ('tipo_combustivel', models.CharField(choices=[('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('flex', 'Flex'), ('diesel', 'Diesel'), ('eletrico', 'Elétrico'), ('hibrido', 'Híbrido')], max_length=20)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('alocado', 'Alocado'), ('manutencao', 'Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='grupo_veiculo.grupoveiculo')),
            ],
        ),
    ]
