# Generated by Django 6.0.5 on 2026-05-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_peca', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PecaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_manutencao', to='manutencao.manutencao')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_manutencao', to='manutencao.peca')),
            ],
        ),
    ]
