# Generated by Django 6.0.4 on 2026-05-24 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.URLField(blank=True, max_length=500, null=True)),
                ('descricao_comercial', models.TextField()),
                ('destaque', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='catalogo', to='veiculo.veiculo')),
            ],
        ),
    ]
