# Generated by Django 6.0.4 on 2026-05-24 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim_prevista', models.DateField()),
                ('data_fim_real', models.DateField(blank=True, null=True)),
                ('km_inicial', models.FloatField()),
                ('km_final', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='alocacao', to='solicitacoes.solicitacao')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAlocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('status_anterior', models.CharField(max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('responsavel_alteracao', models.CharField(max_length=100)),
                ('alocacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='alocacao.alocacao')),
            ],
        ),
    ]
